### ISSUE TITLE
您好，我是一名正在做系统的本科生，想将您的模型嵌入到个性化智能教育系统中，但我该如何进行预测

### ISSUE THREAD

**Issue by npcccccccccccccc** [lswhim/ORCDF#1]
我打算做一个具有个性化学习路径推荐功能的系统（该系统只作为校内课程设计使用，不发布、不涉及商用），想嵌入一个最新的认知诊断/知识追踪模型，请问可以使用ORCDF或者贵校的其他最新模型吗，以及我该如何根据学生的数据预测学生的知识水平

**Comment by lswhim** [comment]
同学您好，首先欢迎您关注我们组的工作，后续如果仍有问题欢迎继续在issue提问或者直接邮件shuoliu@stu.ecnu.edu.cn

**Comment by lswhim** [comment]
同学您好，首先非常感谢您对我们工作的关注！如果后续有任何问题，欢迎继续通过issue提问或发送邮件至shuoliu@stu.ecnu.edu.cn。您可以直接使用我们的ORCDF或其他相关工作，只需在使用时进行引用即可。如果您希望使用自己的数据，请参考我们在https://github.com/ECNU-ILOG/ORCDF/tree/main/datasets/Assist17 提供的数据集进行构建。关于模型训练，可以查看我们提供的sh文件或readme获取详细指导。

关于如何预测学生的知识水平：以ORCDF为例，仓库中的每个模型都有一个名为diagnose()的函数，您可以通过调用diagnose函数直接得到学生的掌握程度。比如https://github.com/ECNU-ILOG/ORCDF/blob/main/inscd/models/static/graph/orcdf.py中的
diagnose函数。
再次感谢您的关注！
