### ISSUE TITLE
您好，非常棒的一篇论文！我想问问对比方法和ORCDF的运行命令行

### ISSUE THREAD

**Issue by zjj1333** [lswhim/ORCDF#2]
1.针对方法ORCDF，if_type=ncd的选择控制将哪种认知诊断模型集成到 ORCDF 中，对应的是论文表2中的OR？：python exp_orcdf.py --method=orcdf --if_type=kancd --data_type=Assist17 --ssl_temp=0.5  --ssl_weight=1e-3  --flip_ratio=0.15  --test_size=0.2 --seed=0 --batch_size=4096 --device=cuda:0 --gcn_layers=3 --epoch=12  --keep_prob=1.0  --lr=4e-3 --weight_decay=0
2.如果我将命令行中的--method换为kancd，对应的是论文表2中的OL？
python exp_orcdf.py --method=kancd --data_type=Assist17 --ssl_temp=0.5  --ssl_weight=1e-3  --flip_ratio=0.15  --test_size=0.2 --seed=0 --batch_size=4096 --device=cuda:0 --gcn_layers=3 --epoch=12  --keep_prob=1.0  --lr=4e-3 --weight_decay=0

![image](https://github.com/user-attachments/assets/17ca683b-a2ab-4a1c-9cf8-39c1e8576a97)

**Comment by lswhim** [comment]
非常感谢您的提问！if_type控制的是认知诊断模型，ncd代表的是NCDM。同理kancd代表KANCD。
关于OL即baseline的运行命令，我们更新了readme，希望能解决您的问题！
