### ISSUE TITLE
您好，想问问如果想用自己的数据集应该怎么处理

### ISSUE THREAD

**Issue by npcccccccccccccc** [lswhim/ORCDF#3]
q矩阵是需要人工构建吗，response.csv分别是user id、question id、0/1吗，这两个文件都需要做什么预处理才能做成您代码需要的形式

**Comment by lswhim** [comment]
非常感谢您的提问

- q_matrix.csv代表的是题目对应知识点的矩阵，形状是题目数目乘以知识点数目。每一行代表其对应的题目考察了哪个知识点，这个需要人工构建。**这里标注的时候要先确定知识点和题目的数目，以便于确定矩阵的维度。**
- response.csv代表的是学生做题记录，就是三元组形式，student_id, exercise_id,response. 比如0,1,1，代表的是0号学生做1号题目做对了。**学生和题目的id是从0开始的，且没有重复情况，比如某个学生做同样一个题两次，这种情况一般会取第一次的结果。**
注意名称要与dataset文件夹内给定的数据文件统一，即q_matrix.csv, response.csv，便于数据读取代码读入。
您只需要把学生做题情况按照要求，处理成上述两个文件即可使用目前的代码。如果有问题，欢迎您继续提问！
